# Generated by Django 4.2.3 on 2023-09-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MH_App', '0006_order_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
