# Generated by Django 4.2.3 on 2023-09-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MH_App', '0008_alter_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
