# Generated by Django 4.2.3 on 2023-09-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MH_App', '0009_alter_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
